[boris]
  version = 1

[build.dist-*]
  git = "refs/heads/master"

[build.branches-*]
  git = "refs/heads/topic/*"

[build.profiling-*]
  git = "refs/heads/profiling/*"

[build.all-*]
  git = "refs/heads/**"
