[boris]
  version = 1

[build.profiling]
  git = "refs/heads/profiling/*"

[build.dist-7-8]
  git = "refs/heads/master"

[build.dist-7-10]
  git = "refs/heads/master"

[build.branches-7-8]
  git = "refs/heads/topic/*"

[build.branches-7-10]
  git = "refs/heads/topic/*"

[build.validate]
  git = "refs/heads/master"
