[boris]
  version = 1

[build.profiling]

[build.dist-7-8]

[build.dist-7-10]

[build.branches-7-8]

[build.branches-7-10]

[build.validate]
  pre = []
  command = [["validate-respect"]]
  success = []
