[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20170330034719-c0ddaf2/master-haskell-20170330034719-c0ddaf2"
  version = 1
  sha1 = "c43b4bc8679f1fcfaba9189c3a0f4cb9fdc6d5a0"

[build.profiling-7-10]
  PROFILING = "true"
  PUBLISH = "true"
  PUBLISH_EXECUTABLES = "warden warden-gen"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_PROFILING"
  GHC_VERSION="7.10.2"
  CABAL_VERSION = "1.22.4.0"

[build.dist-7-10]
  PUBLISH = "true"
  PUBLISH_EXECUTABLES = "warden warden-gen"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"

[build.branches-7-10]
  PUBLISH = "true"
  PUBLISH_EXECUTABLES = "warden warden-gen"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
